# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.IntegerField(blank=True, choices=[(0, 'text')], default=0),
        ),
    ]
